stages:
  - build
  - test

build_driver:
  image: docker:dind
  stage: build
  tags:
    - docker-dind
  script:
    - docker build -t theintegrative/driver:latest .
  rules:
    - changes:
        - Dockerfile

test_driver:
  variables:
  stage: test
  image: theintegrative/driver
  script:
    - curl https://raw.githubusercontent.com/theintegrative/main-driver-setup/opensuse-thinclient/0.sh | bash
