---
- hosts: localhost
  become: yes
  vars:
    ansible_connection: local
    user_name: theintegrative
  handlers:
    - name: Setup git repos
      include_tasks: git-repos.yml

  tasks:
  - name: Install the packages that you mainly use
    package:
      name:
       - keepassxc
       - neovim
       - remmina
       - sudo
       - tmux
       - nmap
       - neofetch
       - docker
       - docker-compose
       - virt-manager
       - ansible
       - python3-pip
       - htop
       - git
      state: latest

  - command: "true"
    notify: Setup git repos
  
  - name: Configure services that run on your system
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
      state: restarted
    loop:
      - docker
