---
- hosts: all
  become: yes
  vars_files:
    - ./vars/main_vars.yml
  roles:
    - role: github
      when: ( first_run == True )
    - role: apt
      when: (ansible_facts['distribution'] == "Ubuntu") and ( testing == False )
    - role: pacman
      when: (ansible_facts['os_family'] == "Archlinux") and ( testing == False )
    - role: dnf
      when: (ansible_facts['distribution'] == "CentOS") and ( testing == False )

  tasks:
  - name: Configure services that run on your system
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
      state: restarted
    loop:
      - docker
    when: 0 > 1
