Vagrant.configure("2") do |config|
  config.vm.define "centos" do |subconfig|
    subconfig.vm.box = "generic/centos9s"
    subconfig.vm.provider "libvirt" do |v|
      v.memory = 10024
      v.cpus = 4
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/configure-main-driver.yml"
    ansible.become = true
  end
end
