- hosts: all
  become: yes
  tasks:
  - name: Refresh repositories and update package openssl
    community.general.zypper:
      name: "{{ packages }}"
      state: present
      update_cache: true

  - name: Configure services that run on your system
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
      state: restarted
    loop: "{{ services }}"
    when: 0 > 1
