- name: Post install opensuse thin client
  hosts: all
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Get packages
      community.general.zypper:
        name: "{{ packages }}"
        state: present
        update_cache: true

    - name: Configure services that run on your system
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: restarted
      loop: "{{ services }}"
      when: 0 > 1
