- hosts: all
  become: yes
  vars:
    user_name: theintegrative
    user_home: "/home/{{ user_name }}/"
    ssh_key: "{{ user_home }}.ssh/id_rsa"
    packages:
      - keepassxc
      - neovim
      - remmina
      - sudo
      - tmux
      - nmap
      - neofetch
      - docker
      - docker-compose
      - virt-manager
      - ansible
      - python3-pip
      - htop
      - git
  tasks:
  - name: Configure services that run on your system
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
      state: restarted
    loop:
      - docker
    when: 0 > 1

