- hosts: all
  become: yes
  vars_files:
    - ./vars/main_vars.yml
  roles:
    - role: github
    - role: dnf
      when: (ansible_facts['distribution'] == "CentOS")

  tasks:
  - name: Configure services that run on your system
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
      state: restarted
    loop:
      - docker
    when: 0 > 1

