user_name: theintegrative
user_home: "/home/{{ user_name }}/"
ssh_key: "{{ user_home }}.ssh/id_rsa"
packages:
  - keepassxc
  - neovim
  - tmux
  - nmap
  - neofetch
  - docker
  - ansible
  - python3-pip
  - htop
  - git
  - glab
services:
  - docker
